### ISSUE TITLE
Hot reload in Docker container

### ISSUE THREAD

**Issue by leonardovilarinho** [vuejs/vuepress#1096]
- [x] I confirm that this is a issue rather than a question.

## Bug report
Automatic reloading does not work in Docker.

#### Version
0.14.2

#### Steps to reproduce

Used `Dockerfile`:
```
FROM node:10.14.1-slim

ENV HOME=/home/app

COPY package.json yarn.lock $HOME/transpiler/

WORKDIR $HOME/transpiler
RUN yarn --silent && yarn cache clean
COPY . $HOME/transpiler

CMD ["yarn", "start"]
```

Used `docker-compose.docs.yml`:
```
version: '2'
services: 
  app:
    build: .
    command: yarn docs:dev
    ports:
      - '8080:8080'
    volumes: 
      - .:/home/app/transpiler
      - /home/app/transpiler/node_modules
```

`scripts` in `package.json`:
```
"scripts": {
    "start": "node source/index.js",
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs" 
}
```

Run `docker-compose -f "docker-compose.docs.yml" up --build`.

#### What is expected?
When I edit the MD files from the documentation, it will load into the container.

#### What is actually happening?
Does not reload the build of vuepress. For this I need to restart the container.

#### Other relevant information

- Your OS: Windows 10
- Node.js version: 10.14.1-slim
- Is this a global or local install?  local
- Which package manager did you use for the install? yarn
