### ISSUE TITLE
Setting to increase content width in CSS

### ISSUE THREAD

**Issue by inianv** [vuejs/vuepress#1867]
Which configuration should be changed to maximize the content width of the rendered markdown files? I would like to make full use of the screen width when view viewing page contents. 

Creating a new `index.styl` file under `.vuepress/styles/` did not work. I created one with a content to increase content width using a CSS property as below. Also tried setting it to `200px`, which didn't work either.

`.content {
  width: 100%;
}`

**Comment by PeppeL-G** [comment]
If I'm not mistaking, it's the following CSS code that limits the width:

```css
.theme-default-content:not(.custom) {
    max-width: 740px;
    margin: 0 auto;
    padding: 2rem 2.5rem;
}
```

Just override the `max-width` using a CSS rule with higher specificity should fix your problem, i.e.:

```css
div.theme-default-content:not(.custom) {
    max-width: 100%
}
```
