### ISSUE TITLE
&shy; and &hyphen; not marked down correctly

### ISSUE THREAD

**Issue by Nastradoomus** [vuejs/vuepress#2186]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Add hyphens manual to styles. Add `&shy;` or `&hyphen;` to .md file(s).

#### What is expected?
Word wrap break word with hyphens.

#### What is actually happening?
HTML is rendered as `&amp;shy; `

#### Other relevant information
[markdown-it](https://markdown-it.github.io/) demo works properly. 

OS: Windows 10 10.0.18362
CPU: (16) x64 Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz
Binaries:
    Node: 13.7.0 - C:\laragon\bin\nodejs\node-v13.7.0\node.EXE
    Yarn: 1.21.1 - C:\laragon\bin\nodejs\node-v13.7.0\yarn.CMD
    npm: 6.13.6 - C:\laragon\bin\nodejs\node-v13.7.0\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: ^1.3.0 => 1.3.0
  npmGlobalPackages:
    vuepress: Not Found

**Comment by meteorlxy** [comment]
Sorry but I cannot reproduce this issue. Things seem to work properly in my case.

In the home page of official docs:

![image](https://user-images.githubusercontent.com/18205362/74625827-9e369200-5188-11ea-9c51-3f1a00ac1947.png)

Result:

![image](https://user-images.githubusercontent.com/18205362/74625837-a989bd80-5188-11ea-9ac9-410a1893d0c0.png)

**Comment by Nastradoomus** [comment]
I was blaming markdown-it but the problem really lies in templating. Sorry for wasting your time. I wasn't thinking clearly.

Please modify index.md

```
---
home: true
heroImage: null
heroText: Shy ex&shy;ample
tagline: Shy ex&shy;ample
actionText: ex&shy;ample
actionLink: example
features:
- title: Shy ex&shy;ample
  details: Shy ex&shy;ample
- title: Vue-Powered
  details: Enjoy the dev experience of Vue + webpack, use Vue components in markdown, and develop custom themes with Vue.
- title: Performant
  details: VuePress generates pre-rendered static HTML for each page, and runs as an SPA once a page is loaded.
footer: Footer
---
# EXAMPLE
Shy ex&shy;ample
```
