### ISSUE TITLE
`sidebar: auto` does not update with document changes

### ISSUE THREAD

**Issue by Enteleform** [vuejs/vuepress#2233]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

1. create a new VuePress project
2. create `./docs/README.md`
   - use setting `sidebar: auto`
   - add some headings & text
3. run `vuepress dev docs --host localhost`
4. delete some of the headings & text

#### What is expected?

1. The main document text will update to reflect the changes.
2. The sidebar will update to reflect the new hierarchy of the document.

#### What is actually happening?

1. ✔️ The main document text reflects the changes.
2. ❌ The sidebar persists the hierarchy of the document that existed previous to the changes.

![VuePress-SidebarIssue](https://user-images.githubusercontent.com/10906415/76996108-4a55cf00-6927-11ea-9a03-04abc93b520a.gif)

#### Other relevant information

- Possibly related to #1399.

- Output of `npx vuepress info` in my VuePress project:

  ```yaml
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 12.6.0 - C:\_\Dev\NodeJS\12\node.EXE
    Yarn: 1.16.0 - C:\_\Dev\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\_\Dev\NodeJS\12\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: ^1.3.1 => 1.4.0
  npmGlobalPackages:
    vuepress: Not Found
```
