### ISSUE TITLE
Documentation - Github Deployment precision

### ISSUE THREAD

**Issue by trolologuy** [vuejs/vuepress#2372]
- [ x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

If you follow the steps described [on the deployment of vuepress github pages](https://v1.vuepress.vuejs.org/guide/deploy.html#github-pages) the deployment fails due to some missing details (configuration of `.travis.yml` file + branching)  in the documentation.

#### What is expected?

The deployment to the github page to be working.

#### What is actually happening?
There is missing information for the case when you are deploying to your "personal space" (I don't know the proper name of it), for example mine is [https://trolologuy.github.io/](https://trolologuy.github.io/).

> If you are deploying to https://<USERNAME or GROUP>.github.io/, you can omit base as it defaults to "/".

As stated on github in the pages setting page (screenshot below), 
> 'User pages must be built from the master branch.'  
That means that the generated static files from `docs/.vuepress/dist` should be pushed into master.

![github-pages-settings](https://user-images.githubusercontent.com/16886290/81048032-d9a94880-8ebb-11ea-8415-92a6e330ec9c.png)

That also means that the `target_branch` option is missing in the `.travis.yml`file.
I added it below commented out:
``` yml
language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn docs:build # npm run docs:build
deploy:
  provider: pages
  # Uncomment the following line if you wish to deploy to https://<USERNAME or GROUP>.github.io/
  # target_branch: master
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN # A token generated on GitHub allowing Travis to push code on you repository. Set in the Travis settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
```

The explanation that could be added on the documentation could be:
> If you are deploying to https://<USERNAME or GROUP>.github.io/, you can omit base as it defaults to "/".
> Be aware that your generated static files have to be present on the `master` branch of your repository (github pages technical limitation). 
> This could be solved for example by creating a `sources` branch where you would put the source code of your project. This can be achieved with 
> ```
> git checkout -b sources
> git push origin sources
> ```
> To enable travis to push to the `master` branch, please uncomment the line `# target_branch: master` by removing the `#`.  
> Final step would be to add the files to your branch (for e.g with `git add *`) and push your files to the remote branch (`git push origin sources`).

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:
