### ISSUE TITLE
sass-loader, Issue with factoring out coefficient from calc

### ISSUE THREAD

**Issue by hosseinamin** [vuejs/vuepress#2433]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce

using `vuepress@1.4.1` .

The converted css of the following is not right. But I've checked with `node-sass` the issue is not is sass. Instead it is in some kind of minifier or something when you build the vuepress. Not as client mode..

Here's the project I found the issue in, https://github.com/AceCentre/SpeakBook/

https://github.com/sass/sass/issues/2868

``` scss
.b4x {
  width: calc(var(--block-width) * 4 + var(--block-margin) * 4);
}
```

#### What is expected?

``` css
.b4x {
  width: calc(4 * (var(--block-width) + var(--block-margin)));
}
```

#### What is actually happening?

``` css
.b4x {
  width: calc(var(--block-width) + var(--block-margin));
}
```

#### Workaround

Factor out the coefficient manually.
```
.b4x {
  width: calc(4 * (var(--block-width) + var(--block-margin)));
}
```
