### ISSUE TITLE
Having to use !important to override inbuilt style rules for algolia

### ISSUE THREAD

**Issue by JayMcConnon** [vuejs/vuepress#2470]
- [x ] I confirm that this is an issue rather than a question.

#### Steps to reproduce
Install vuepress

Get indexed by algolia search

Add the config to config.js

Add some rules to index.styl

Most of the rules for the colors for the search bar are inherited i think from the default pallete variables correctly as i didn't configure anything but most of the colours matched my chosen pallete but the highlight was still the default green color from the inbuilt component. 

in my case i added the following to the index.styl to customise 

```css
.algolia-autocomplete .algolia-docsearch-suggestion--highlight {
  color: #07296d;
  background: rgba(30, 90, 158, 0.20);
}
```

But no effect on the highlighting of the file until i added important flag as the styles were being overridden in the default component. 

So i have added important

```css
.algolia-autocomplete .algolia-docsearch-suggestion--highlight {
  color: #07296d !important;
  background: rgba(30, 90, 158, 0.20) !important;
}
```

#### What is expected?

Adding algolia customisation rules into index.styl should customise the look of the search bar output

#### What is actually happening?

nothing until i add !important to my rules

#### Other relevant information

Unless i am misunderstanding something about customising the layout this is a bug, if not then feel free to let me know how i should be doing things.
