### ISSUE TITLE
Deploy in Gitlab

### ISSUE THREAD

**Issue by LocTran016** [vuejs/vuepress#2584]
In your guide how to [deploy vuepress on Gitlab](https://vuepress.vuejs.org/guide/deploy.html#github-pages), I have found that put these code in .gitlab-ci.yml may cause issue if you are using extension need node.js 10+ and it is recommend to use the node.js 10+ as well
``` 
image: node:9.11.1

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn install # npm install
  - yarn docs:build # npm run docs:build
  artifacts:
    paths:
    - public
  only:
  - master
```
The `image: node:9.11.1` mean that the gitlab-ci will use node.js 9.11.1 which may cause issue somehow. I don't know if you could update the guide, maybe change `node:9.11.1` into `node:14.8.0` or something newer than node.js 10. Thanks for reading my issue.
Although this maybe unnecessary, here is my project if you want that: https://gitlab.com/LocTran016/genetics
