### ISSUE TITLE
Can not have multiple meta "article:tag"

### ISSUE THREAD

**Issue by taichunmin** [vuejs/vuepress#2614]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Write multiple meta article:tag in frontmatter

```yaml
meta:
  - property: article:tag
    content: tag1
  - property: article:tag
    content: tag2
  - property: article:tag
    content: tag3
```

#### What is expected?

```html
<meta property="article:tag" content="tag1">
<meta property="article:tag" content="tag2">
<meta property="article:tag" content="tag3">
```

#### What is actually happening?

```html
<meta property="article:tag" content="tag1">
```

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

https://github.com/vuejs/vuepress/blob/3c94f711434ae7fd5f983ca19c8a2c29ef22e855/packages/%40vuepress/core/lib/client/root-mixins/updateMeta.js#L36

Need to patch `getMergedMetaTags()`
