### ISSUE TITLE
Could be possible to insert a link in the metadata?

### ISSUE THREAD

**Issue by aguadotzn** [vuejs/vuepress#2673]
I am just wondering if we can put a link to another part of the project inside the metadata of any page. For example, in [this case](https://vuepress.vuejs.org/theme/default-theme-config.html#homepage) I want to **include a link** in the details of any feature. Could be possible? How to do this? 

```
---
home: true
heroImage: /hero.png
heroText: Hero Title
tagline: Hero subtitle
actionText: Get Started →
actionLink: /guide/
features:
- title: Simplicity First
  details: Minimal setup with markdown-centered project structure helps you focus on writing.
- title: Vue-Powered
  details: Enjoy the dev experience of Vue + webpack, use Vue components in markdown, and develop custom themes with Vue.
- title: Performant
  details: VuePress generates pre-rendered static HTML for each page, and runs as an SPA once a page is loaded.
footer: MIT Licensed | Copyright © 2018-present Evan You
---
```

I just try with `[vue link](vuejs.org)`but is not actually possible inside YAML metadata. Thanks in advance.
