### ISSUE TITLE
[Feature Request] Default Theme Home could have links in each feature section.

### ISSUE THREAD

**Issue by kertof** [vuejs/vuepress#2692]
## Feature request

In hte default theme, having severl features is great, I'd like to have links in each feature section to send the user to each feature.

#### What problem does this feature solve?
This will simplify navigation on the website.

#### What does the proposed API look like? / How should this be implemented in your opinion?
In the frontmatter:
```yaml
features:
  - title: Feature 1 Title
    details: Feature 1 Description
    actionText: Quick Start →
    actionLink: /feature-1/
  - title: Feature 2 Title
    details: Feature 2 Description
    actionText: Quick Start →
    actionLink: /feature-12/
  - title: Feature 3 Title
    details: Feature 3 Description
```

This uses the same API as the hero actiontext and action link.

#### Are you willing to work on this yourself?
Yes
