### ISSUE TITLE
 .vuepress/styles/index.styl can't override theme style

### ISSUE THREAD

**Issue by yzhang921** [vuejs/vuepress#2886]
## Screenshots

docs/.vuepress/styles/index.styl

add a user style

```css
.navbar {
  box-shadow: 0 2px 3px var(--card-shadow-color);
}
```

![image](https://user-images.githubusercontent.com/6037522/124059246-581c5e80-da5d-11eb-8aeb-a372e7b6c86e.png)

![image](https://user-images.githubusercontent.com/6037522/124059175-36bb7280-da5d-11eb-9ec9-fc663e919edf.png)
