### ISSUE TITLE
gitlab pages deploy failed, missing pages artifacts

### ISSUE THREAD

**Issue by e7** [vuejs/vuepress#3028]
Here is my .gitlab-ci.yml
```yaml
image: node:12.22.11
pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn install # npm install
  - yarn docs:build # npm run docs:build
  artifacts:
    paths:
    - public
  only:
  - feature/vuepress
```
