### ISSUE TITLE
overwrite css ".content:not(.custom) img" not working

### ISSUE THREAD

**Issue by MurWhite** [vuejs/vuepress#449]
I tried to overwrite css `.content:not(.custom) img` in `override.styl`:
```css
.content:not(.custom) img{
  max-width: unset;
  }
```
But it seems not working because the default one overwrite the `override.styl`:
![image](https://user-images.githubusercontent.com/15206570/40058272-44a27aa6-5883-11e8-9717-5ebcd4f8830e.png)
`
And I found that this default css could overwrite any other css:
![image](https://user-images.githubusercontent.com/15206570/40058645-5e7db6ec-5884-11e8-9ba4-720729516314.png)

Obviously I couldn't use `!import` with `voerride.styl` or my custom component.

**Comment by ulivz** [comment]
Hmmm, It's about css general knowledge. Try `#app .content:not(.custom) img`.

**Comment by MurWhite** [comment]
@ulivz OK, that's my bad. But what this commit https://github.com/vuejs/vuepress/commit/145cf4f did with the default css rule: 
```css
 .content:not(.custom) img {max-width: 100%}
``` 
can be merged into one css rule: 
```css
 .content img {max-width: 100%;}
```
This can lower the priority of the default css(from 0,0,2,1 to 0,0,1,1), meanwhile it will be convenient for other custom css.

related: [how css priority rules calculated](https://www.codeavengers.com/notes/priority-rules#menu-how-is-it-calculated)
