### ISSUE TITLE
background image on home page

### ISSUE THREAD

**Issue by bertdeterd** [vuejs/vuepress#684]
## Feature request

i would like to set a background image to the home page in frontmatter like:
![image](https://user-images.githubusercontent.com/5920136/43396530-20fa2f4e-9402-11e8-86a5-f593b1e30596.png)

#### What problem does this feature solve?
Nice look and feel

#### What does the proposed API look like?
See screenshot

#### How should this be implemented in your opinion?
I do not know if this already should be possible.

**Comment by ulivz** [comment]
We don't plan to add this feature to default theme, since it's easy to be done at user-land.

``` css
/* .vuepress/style.styl */
.home {
  background-image: url(/hero.png)
}
```

Ref: https://vuepress.vuejs.org/default-theme-config/#simple-css-override
